

DEFAULT_CONFIG = {
    'Global': {
        'char_only': False,
        'recognition_only': False,
        'skip_line_detection': False,
        'wandb_project': None
    },
    'Recognizer': {
        'char': {
            'adamw_beta1': 0.9,
            'adamw_beta2': 0.999,
            'ascender': True,
            'aug_paired': False,
            'batch_size': 128,
            'char_only_sampler': False,
            'char_trans_version': 2,
            'dec_lr_factor': 0.9,
            'default_font_name': 'Noto',
            'diff_sizes': False,
            'epoch_viz_dir': None,
            'expansion_factor': 1,
            'few_shot': None,
            'finetune': False,
            'font_dir_path': None,
            'hardneg_k': 8,
            'high_blur': False,
            'hns_txt_path': None,
            'huggingface_model': None,
            'imsize': 224,
            'int_eval_steps': None,
            'latin_suggested_augs': True,
            'lr': 0.002,
            'lr_schedule': False,
            'm': 4,
            'model_backend': 'timm',
            'model_dir': './char_model',
            'no_aug': False,
            'num_cores': None,
            'num_epochs': 10,
            'num_passes': 1,
            'pretrain': False,
            'providers': None,
            'ready_to_go_data_dir_path': None,
            'render_dict': None,
            'start_epoch': 1,
            'temp': 0.1,
            'test_at_end': True,
            'test_set_from_coco_json': None,
            'timm_model_name': 'mobilenetv3_small_050.lamb_in1k',
            'train_set_from_coco_json': None,
            'train_val_test_split': [0.7, 0.15, 0.15],
            'val_set_from_coco_json': None,
            'weight_decay': 0.0005
        },
        'word': {
            'adamw_beta1': 0.9,
            'adamw_beta2': 0.999,
            'ascender': True,
            'aug_paired': False,
            'batch_size': 128,
            'char_only_sampler': False,
            'char_trans_version': 2,
            'dec_lr_factor': 0.9,
            'default_font_name': 'Noto',
            'diff_sizes': False,
            'epoch_viz_dir': None,
            'expansion_factor': 1,
            'few_shot': None,
            'finetune': False,
            'font_dir_path': None,
            'hardneg_k': 8,
            'high_blur': False,
            'hns_txt_path': None,
            'huggingface_model': None,
            'imsize': 224,
            'int_eval_steps': None,
            'latin_suggested_augs': True,
            'lr': 0.002,
            'lr_schedule': False,
            'm': 4,
            'model_backend': 'timm',
            'model_dir': './word_model',
            'no_aug': False,
            'num_cores': None,
            'num_epochs': 10,
            'num_passes': 1,
            'pretrain': False,
            'providers': None,
            'ready_to_go_data_dir_path': None,
            'render_dict': None,
            'start_epoch': 1,
            'temp': 0.1,
            'test_at_end': True,
            'test_set_from_coco_json': None,
            'timm_model_name': 'mobilenetv3_small_050.lamb_in1k',
            'train_set_from_coco_json': None,
            'train_val_test_split': [0.7, 0.15, 0.15],
            'val_set_from_coco_json': None,
            'weight_decay': 0.0005
        }
    },
    'Localizer': {
        'batch_size': 16,
        'conf_thresh': 0.25,
        'device': 'cpu',
        'epochs': 10,
        'huggingface_model': None,
        'input_shape': [640, 640],
        'iou_thresh': 0.1,
        'max_det': 200,
        'mmdet_config': None,
        'model_backend': 'yolov5',
        'model_dir': './localizer_model',
        'num_cores': None,
        'providers': None,
        'vertical': False,
        'visualize': None
    },
    'Line': {
        'batch_size': 16,
        'conf_thresh': 0.2,
        'device': 'cpu',
        'epochs': 10,
        'huggingface_model': None,
        'input_shape': [640, 640],
        'iou_thresh': 0.15,
        'max_det': 200,
        'min_seg_ratio': 2,
        'model_backend': 'yolov5',
        'model_dir': './line_model',
        'num_cores': None,
        'onnx': None,
        'providers': None,
        'visualize': None
    },
}

