Global:
  wandb_project: effocr_package_test_locca

Recognizer:
  word:
    output_dir: ./effocr_package_test_locca_word
    font_dir_path: >-
      /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187
      /jake_github_repos/ocr-as-retrieval/english_font_files
    model_backend: timm
    timm_model_name: mobilenetv3_small_050.lamb_in1k
    render_dict: >-
      /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/e2e2e/
      end-to-end-pipeline/pipeline_egress/silver_dpd/full_wordlist_effocr.txt
    ready_to_go_data_dir_path: >-
      /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/word_level_effocr/
      fullsym_locc_dict_words_paired_silver/images
    pretrained_model_dir:
    train_val_test_split: [0.7, 0.15, 0.15]
    batch_size: 256
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 1
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 224
    char_trans_version: 4
    hardneg_k: 8
    num_passes: 1
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
  char:
    output_dir: ./effocr_package_test_locca_char
    font_dir_path: >- 
      /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/
      ocr-as-retrieval/english_font_files
    model_backend: timm
    timm_model_name: mobilenetv3_small_050.lamb_in1k
    render_dict: >-
      /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/
      ocr-as-retrieval/english_charsets/allchars.txt
    ready_to_go_data_dir_path: >-
      /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/ocr_char_crops/locca
    pretrained_model_dir:
    train_val_test_split: [0.7, 0.15, 0.15]
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 30
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 224
    char_trans_version: 4
    hardneg_k: 8
    num_passes: 40
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
