Global:
  wandb_project: effocr_package_test_locca
  recognition_only: true
  char_only: true

Recognizer:
  char:
    model_output_dir: ./effocr_package_test_tk_HNS
    font_dir_path: /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/japan_font_files
    model_backend: timm
    timm_model_name: mobilenetv3_small_050.lamb_in1k
    render_dict: 
      - /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/japan_charsets/adobe_1_7_unicodes.txt
      - /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/japan_charsets/jisx0213_unicodes.txt
    ready_to_go_data_dir_path: /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/ocr_char_crops/tk
    pretrained_model_dir:
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot:
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 20
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 224
    char_trans_version: 1
    hardneg_k: 8
    num_passes: 1
    expansion_factor: 1
    default_font_name: Noto
    ascender: False
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: False
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: ./effocr_package_test_tk_HNS/hns.txt
    epoch_viz_dir:
