Global:
  wandb_project: effocr_package_test_locca
  recognition_only: true
  char_only: true
  skip_line_detection: true

Recognizer:
  char:
    model_output_dir: ./effocr_demo_tk
    font_dir_path: /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/japan_font_files
    model_backend: timm
    timm_model_name: edgenext_xx_small.in1k # mobilenetv3_small_050.lamb_in1k
    render_dict: 
      - /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/japan_charsets/adobe_1_7_unicodes.txt
      - /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/japan_charsets/jisx0213_unicodes.txt
    ready_to_go_data_dir_path: /content/drive/ocr_char_crops/tk
    pretrained_model_dir:
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot: 10
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 20
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 256
    char_trans_version: 1
    hardneg_k: 8
    num_passes: 1
    expansion_factor: 1
    default_font_name: Noto
    ascender: False
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: False
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
    train_set_from_coco_json:
    val_set_from_coco_json:
    test_set_from_coco_json: 
    huggingface_model:


Localizer: 
  model_path: 
  mmdet_config: 
  iou_thresh: 0.10
  conf_thresh: 0.25 
  onnx_providers: 
  input_shape: (640, 640)
  model_backend: yolo
  visualize: 
  num_cores: 
  max_det: 200
  vertical: True
  training_name: effocr_tk_fs_localizer
  epochs: 50
  batch_size: 16
  vertical: False
  device: cpu
  huggingface_model: dell-research-harvard/effocr_demo/best.pt
