Global:
  wandb_project: effocr_package_test_locca
  recognition_only: false
  char_only: false

Recognizer:
  word:
    model_output_dir: ./effocr_package_test_locca_word2
    font_dir_path: /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/english_font_files
    model_backend: onnx
    timm_model_name: mobilenetv3_small_050.lamb_in1k
    render_dict: 
      - /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/e2e2e/end-to-end-pipeline/pipeline_egress/silver_dpd/full_wordlist_effocr.txt
    ready_to_go_data_dir_path: /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/word_level_effocr/fullsym_locc_dict_words_paired_silver/images
    pretrained_model_dir: ./models/yolo/word_recognizer_new
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot:
    batch_size: 256
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 1
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 224
    char_trans_version: 2
    hardneg_k: 8
    num_passes: 1
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
    train_set_from_coco_json:
    val_set_from_coco_json:
    test_set_from_coco_json:
    num_cores:
    providers:
  char:
    model_output_dir: ./effocr_package_test_locca_char2
    font_dir_path: /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/english_font_files
    model_backend: onnx
    timm_model_name: mobilenetv3_small_050.lamb_in1k
    render_dict: 
      - /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/jake_github_repos/ocr-as-retrieval/english_charsets/allchars.txt
    ready_to_go_data_dir_path: /mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/ocr_char_crops/locca
    pretrained_model_dir: ./models/yolo/char_recognizer
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot: 
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 30
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 224
    char_trans_version: 2
    hardneg_k: 8
    num_passes: 40
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
    train_set_from_coco_json:
    val_set_from_coco_json:
    test_set_from_coco_json:
    num_cores:
    providers:

Localizer: 
  model_path: ./models/yolo/localizer_model.pt
  mmdet_config: 
  iou_thresh: 0.10
  conf_thresh: 0.25 
  onnx_providers: 
  input_shape: (640, 640)
  model_backend: yolo
  visualize: 
  num_cores: 
  max_det: 200
  vertical: False
  training_name: effocr_localizer
  epochs: 50
  batch_size: 16
  vertical: False
  device: cpu
  huggingface_model: 


Line:
  model_path: 
  iou_thresh: 0.15
  conf_thresh: 0.20
  num_cores:
  providers:
  input_shape: (640, 640)
  model_backend: yolo
  min_seg_ratio: 2
  visualize: 
  max_det: 200
  training_name: effocr_line
  epochs: 50
  batch_size: 16
  device: cpu
  huggingface_model: dell-research-harvard/effocr_en/line_model.pt