Global:
  wandb_project: name_of_wandb_project_for_effocr
  recognition_only: false
  char_only: false

Recognizer:
  word:
    model_output_dir: /path/to/word/model/output
    font_dir_path: /path/to/dir/of/font/files/for/synthetic/rendering
    model_backend: timm
    timm_model_name: mobilenetv3_small_050.lamb_in1k
    render_dict: 
      - /path/to/list/of/words/to/render
      - /another/path/to/list/of/words/to/render
    ready_to_go_data_dir_path: /path/to/dir/of/preformed/training/data/from/previous/run
    pretrained_model_dir: /path/to/pretrained/model/output/dir
    num_epochs: 20
    num_passes: 1
    start_epoch: 1
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot:
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    temp: 0.1
    m: 4
    imsize: 224
    char_trans_version: 2
    hardneg_k: 8
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
    train_set_from_coco_json:
    val_set_from_coco_json:
    test_set_from_coco_json:
    num_cores:
    providers:
  char:
    model_output_dir: /path/to/char/model/output
    font_dir_path: /path/to/dir/of/font/files/for/synthetic/rendering
    model_backend: timm
    timm_model_name: mobilenetv3_small_050.lamb_in1k
    render_dict: 
      - /path/to/list/of/chars/to/render
      - /another/path/to/list/of/chars/to/render
    ready_to_go_data_dir_path: /path/to/dir/of/preformed/training/data/from/previous/run
    pretrained_model_dir: /path/to/pretrained/model/output/dir
    num_epochs: 20
    num_passes: 1
    start_epoch: 1
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot:
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    temp: 0.1
    m: 4
    imsize: 224
    char_trans_version: 2
    hardneg_k: 8
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
    train_set_from_coco_json:
    val_set_from_coco_json:
    test_set_from_coco_json:
    num_cores:
    providers:

Localizer: 
  model_path: /path/to/localizer/model
  mmdet_config:
  iou_thresh: 0.10
  conf_thresh: 0.25 
  onnx_providers: 
  input_shape: (640, 640)
  model_backend: yolo
  visualize: 
  num_cores: 
  max_det: 200
  vertical: False
  training_name: name_of_training_run
  epochs: 50
  batch_size: 16
  vertical: False
  device: cpu


Line:
  model_path: /path/to/line/detection/model
  iou_thresh: 0.15
  conf_thresh: 0.20
  num_cores:
  providers:
  input_shape: (640, 640)
  model_backend: yolo
  min_seg_ratio: 2
  visualize: 
  max_det: 200
  training_name: name_of_training_run
  epochs: 50
  batch_size: 16
  device: cpu