Global:
  wandb_project: 
  recognition_only: false
  char_only: false
  skip_line_detection: false

Recognizer:
  word:
    model_dir: ./word_model
    font_dir_path:
    render_dict:
    ready_to_go_data_dir_path:
    pretrained_model_dir: 
    model_backend: timm
    timm_model_name:
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot:
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 10
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 224
    char_trans_version: 2
    hardneg_k: 8
    num_passes: 1
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
    train_set_from_coco_json:
    val_set_from_coco_json:
    test_set_from_coco_json:
    num_cores:
    providers:
    huggingface_model:

  char:
    model_dir: ./char_model
    font_dir_path:
    render_dict:
    ready_to_go_data_dir_path:
    pretrained_model_dir: 
    model_backend: timm
    timm_model_name:
    train_val_test_split: [0.7, 0.15, 0.15]
    few_shot: 
    batch_size: 128
    lr: 2.0e-3
    dec_lr_factor: 0.9
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    weight_decay: 5.0e-4
    num_epochs: 10
    temp: 0.1
    start_epoch: 1
    m: 4
    imsize: 224
    char_trans_version: 2
    hardneg_k: 8
    num_passes: 1
    expansion_factor: 1
    default_font_name: Noto
    ascender: True
    finetune: False
    pretrain: False
    high_blur: False
    latin_suggested_augs: True
    diff_sizes: False
    test_at_end: True
    no_aug: False
    lr_schedule: False
    char_only_sampler: False
    aug_paired: False
    int_eval_steps:
    hns_txt_path: 
    epoch_viz_dir:
    train_set_from_coco_json:
    val_set_from_coco_json:
    test_set_from_coco_json:
    num_cores:
    providers:
    huggingface_model:

Localizer:
  training_name: localizer_model
  model_path: 
  mmdet_config: 
  iou_thresh: 0.10
  conf_thresh: 0.25 
  input_shape: [640, 640]
  model_backend: yolo
  visualize: 
  num_cores: 
  max_det: 200
  vertical: False
  epochs: 50
  batch_size: 16
  vertical: False
  device: cpu
  onnx_providers:
  huggingface_model:

Line:
  training_name: line_model
  model_path: 
  iou_thresh: 0.15
  conf_thresh: 0.20
  num_cores:
  providers:
  input_shape: [640, 640]
  model_backend: yolov5
  min_seg_ratio: 2
  visualize: 
  max_det: 200
  epochs: 50
  batch_size: 16
  device: cpu
  onnx:
  huggingface_model:
  